#!/usr/bin/python3
'''
    +  加
    -  减
    *  乘
    /  除
    %  取模
    ** 幂
    // 取整除
'''
a = 21
b = 10
c = 0
c = a + b
print(c)
c= a - b
print(c)
c= a * b
print(c)
c= a / b
print(c)

c= a % b
print(c)

a=2
b=3
c = a**3
print(c)
a=10
b=5
c=a//b
print(c)

''' 
    数学函数
    abs(x) 返回数字的绝对值，如abs(-10) 返回10
    ceil(x)返回数字的上入整数 如 math.ceil(4.1)返回5
    exp(x) 返回e的x次幂(ex)，如math.exp(1)返回
    fabs(x)返回数字的绝对值，如math.fabs(-10)返回10.0
    floor(x)返回 数字的下舍整数，如math.floor(4.9)返回4
    log(x) 如 math.log(math.e) 返回1.0 math.log(100,10)返回2.0
    log10(x) 返回以10为技术的x 的对数，如math.log10(100)返回2.0
    max(x1,x2...) 返回给定参数的最大值，参数可以为序列
    max(x1,x2...) 返回给定参数的最小值，参数可以为序列
    modf(x) 返回x的整数部分与小数部分，两部分的数值符合与x 相同，整数部分以浮点型表示
    pow(x,y) x** 运算后因的值
    round(x,[n]) 返回浮点x 的四舍五入值，如给出n值，则代表舍入到小数点后的位数
    sqrt(x) 返回数字x 的平方根
'''

var1='Hello World'
print(var1)
print("已更新字符串：",var1[:6] + 'Runoob')

